### ISSUE TITLE
Problem deploying single node

### ISSUE THREAD

**Issue by fabrizio8** [wazuh/wazuh-docker#1423]
I've followed the exact instructions from [the docs](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html) to generate certs and deploy the cluster.

After a handful of attempts, I'm not sure how to get this to work. Most similar issues I find reference to seem to be very old and related to some different issue. I'm using ubuntu server 24 and I'm just trying to get a default deployment going.

These some logs I thought may be relevant.

`single-node-wazuh.manager-1    | 2024-07-06T00:45:02.894Z       ERROR   [publisher_pipeline_output]     pipeline/output.go:154  Failed to connect to backoff(elasticsearch(https://wazuh.indexer:9200)): Get "https://wazuh.indexer:9200": dial tcp 172.24.0.2:9200: connect: connection refused
single-node-wazuh.manager-1    | 2024-07-06T00:45:02.895Z       INFO    [publisher_pipeline_output]     pipeline/output.go:145  Attempting to reconnect to backoff(elasticsearch(https://wazuh.indexer:9200)) with 2 reconnect attempt(s)`

`single-node-wazuh.manager-1    | 2024-07-06T00:44:57.664Z       INFO    instance/beat.go:299    Setup Beat: filebeat; Version: 7.10.2
single-node-wazuh.manager-1    | 2024-07-06T00:44:57.666Z       INFO    eslegclient/connection.go:99    elasticsearch url: https://wazuh.indexer:9200
single-node-wazuh.manager-1    | 2024-07-06T00:44:57.667Z       INFO    [publisher]     pipeline/module.go:113  Beat name: wazuh.manager
single-node-wazuh.manager-1    | 2024-07-06T00:44:57.670Z       INFO    beater/filebeat.go:117  Enabled modules/filesets: wazuh (alerts),  ()
single-node-wazuh.manager-1    | 2024-07-06T00:44:57.671Z       INFO    instance/beat.go:455    filebeat start running.
single-node-wazuh.manager-1    | 2024-07-06T00:44:57.672Z       INFO    memlog/store.go:119     Loading data file of '/var/lib/filebeat/registry/filebeat' succeeded. Active transaction id=0
single-node-wazuh.manager-1    | 2024-07-06T00:44:57.673Z       INFO    memlog/store.go:124     Finished loading transaction log file for '/var/lib/filebeat/registry/filebeat'. Active transaction id=16
single-node-wazuh.manager-1    | 2024-07-06T00:44:57.673Z       INFO    [registrar]     registrar/registrar.go:109      States Loaded from registrar: 1
single-node-wazuh.manager-1    | 2024-07-06T00:44:57.673Z       INFO    [crawler]       beater/crawler.go:71    Loading Inputs: 1
single-node-wazuh.manager-1    | 2024-07-06T00:44:57.674Z       INFO    log/input.go:157        Configured paths: [/var/ossec/logs/alerts/alerts.json]
single-node-wazuh.manager-1    | 2024-07-06T00:44:57.674Z       INFO    [crawler]       beater/crawler.go:141   Starting input (ID: 9132358592892857476)
single-node-wazuh.manager-1    | 2024-07-06T00:44:57.674Z       INFO    [crawler]       beater/crawler.go:108   Loading and starting Inputs completed. Enabled inputs: 1
single-node-wazuh.manager-1    | 2024-07-06T00:44:57.675Z       INFO    log/harvester.go:302    Harvester started for file: /var/ossec/logs/alerts/alerts.json
single-node-wazuh.dashboard-1  | {"type":"log","@timestamp":"2024-07-06T00:44:57Z","tags":["error","opensearch","data"],"pid":54,"message":"[ConnectionError]: connect ECONNREFUSED 172.24.0.2:9200"}
single-node-wazuh.manager-1    | 2024-07-06T00:44:58.676Z       INFO    [publisher_pipeline_output]     pipeline/output.go:143  Connecting to backoff(elasticsearch(https://wazuh.indexer:9200))
single-node-wazuh.manager-1    | 2024-07-06T00:44:58.676Z       INFO    [publisher]     pipeline/retry.go:219   retryer: send unwait signal to consumer
single-node-wazuh.manager-1    | 2024-07-06T00:44:58.676Z       INFO    [publisher]     pipeline/retry.go:223     done
single-node-wazuh.indexer-1    | [2024-07-06T00:45:00,115][INFO ][o.o.p.c.c.PluginSettings ] [wazuh.indexer] Trying to create directory /dev/shm/performanceanalyzer/.
single-node-wazuh.indexer-1    | [2024-07-06T00:45:00,116][INFO ][o.o.p.c.c.PluginSettings ] [wazuh.indexer] Config: metricsLocation: /dev/shm/performanceanalyzer/, metricsDeletionInterval: 1, httpsEnabled: false, cleanup-metrics-db-files: true, batch-metrics-retention-period-minutes: 7, rpc-port: 9650, webservice-port 9600
single-node-wazuh.manager-1    | 2024-07-06T00:45:00.311Z       ERROR   [publisher_pipeline_output]     pipeline/output.go:154  Failed to connect to backoff(elasticsearch(https://wazuh.indexer:9200)): Get "https://wazuh.indexer:9200": dial tcp 172.24.0.2:9200: connect: connection refused
single-node-wazuh.manager-1    | 2024-07-06T00:45:00.311Z       INFO    [publisher_pipeline_output]     pipeline/output.go:145  Attempting to reconnect to backoff(elasticsearch(https://wazuh.indexer:9200)) with 1 reconnect attempt(s)
single-node-wazuh.manager-1    | 2024-07-06T00:45:00.311Z       INFO    [publisher]     pipeline/retry.go:219   retryer: send unwait signal to consumer
single-node-wazuh.manager-1    | 2024-07-06T00:45:00.311Z       INFO    [publisher]     pipeline/retry.go:223     done
single-node-wazuh.dashboard-1  | {"type":"log","@timestamp":"2024-07-06T00:45:00Z","tags":["error","opensearch","data"],"pid":54,"message":"[ConnectionError]: connect ECONNREFUSED 172.24.0.2:9200"}
single-node-wazuh.indexer-1    | [2024-07-06T00:45:00,778][INFO ][o.o.i.r.ReindexPlugin    ] [wazuh.indexer] ReindexPlugin reloadSPI called`

`single-node-wazuh.indexer-1    | [2024-07-06T00:46:10,789][INFO ][o.o.i.i.MetadataService  ] [wazuh.indexer] ISM config index not exist, so we cancel the metadata migration job.
single-node-wazuh.dashboard-1  | {"type":"error","@timestamp":"2024-07-06T00:46:19Z","tags":["connection","client","error"],"pid":54,"level":"error","error":{"message":"C0F74F2E95740000:error:0A000418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 48\n","name":"Error","stack":"Error: C0F74F2E95740000:error:0A000418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 48\n","code":"ERR_SSL_TLSV1_ALERT_UNKNOWN_CA"},"message":"C0F74F2E95740000:error:0A000418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 48\n"}
single-node-wazuh.indexer-1    | [2024-07-06T00:46:23,055][WARN ][o.o.s.a.BackendRegistry  ] [wazuh.indexer] Authentication finally failed for admin from 172.24.0.4:37330
single-node-wazuh.dashboard-1  | {"type":"log","@timestamp":"2024-07-06T00:46:23Z","tags":["error","http","server","OpenSearchDashboards"],"pid":54,"message":"Error: Authentication Exception\n    at SecurityClient.authinfo (/usr/share/wazuh-dashboard/plugins/securityDashboards/server/backend/opensearch_security_client.ts:118:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at /usr/share/wazuh-dashboard/plugins/securityDashboards/server/auth/types/authentication_type.ts:208:18\n    at Object.interceptAuth [as authenticate] (/usr/share/wazuh-dashboard/src/core/server/http/lifecycle/auth.js:112:22)\n    at exports.Manager.execute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at module.exports.internals.Auth._authenticate (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/auth.js:273:30)\n    at Request._lifecycle (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._execute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/request.js:281:9)"}
single-node-wazuh.dashboard-1  | {"type":"error","@timestamp":"2024-07-06T00:46:22Z","tags":[],"pid":54,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toInternalError (/usr/share/wazuh-dashboard/src/core/server/http/router/response_adapter.js:80:19)\n    at Object.interceptAuth [as authenticate] (/usr/share/wazuh-dashboard/src/core/server/http/lifecycle/auth.js:151:34)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at exports.Manager.execute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at module.exports.internals.Auth._authenticate (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/auth.js:273:30)\n    at Request._lifecycle (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._execute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/request.js:281:9)"},"url":"https://10.0.0.9/","message":"Internal Server Error"}`

**Comment by fabrizio8** [comment]
The issue was using the snap installation (installed by enabling the 'docker' option at the end of the Ubuntu Server installation) of docker vs following the official steps from the docker website.
Using the non-snap installation resulted in a functional wazuh cluster.
