### ISSUE TITLE
Editing and uploading configuration file fails

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-docker#176]
Hi,

When editing the `ossec.conf` in Kibana (Management > Configuration) It seems that something is wrong with the Wazuh API when saving the file.

Apparently, the change is done correctly, but the API returns a `1000: Internal error` error.
After digging into this, we've noticed that it's just happening with the `ossec.conf` file, but not with editing rules (local_rules.xml), so we're afraid that something wrong with the volumes and their involved filesystems may be happening.

A paste of the trace, debugged within the container:
```
>>> upload_file('tmp/api_group_conf_1557503379_60', 'etc/ossec.conf', 'application/xml', overwrite=True)
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.7/shutil.py", line 563, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/var/ossec/tmp/api_tmp_file_1557503748.2873518_690.xml' -> '/var/ossec/etc/ossec.conf'
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/manager.py", line 212, in upload_file
    return upload_xml(file_data, path)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/manager.py", line 280, in upload_xml
    raise e
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/manager.py", line 269, in upload_xml
    move(tmp_file_path, new_conf_path)
  File "/var/ossec/framework/python/lib/python3.7/shutil.py", line 577, in move
    copy_function(src, real_dst)
  File "/var/ossec/framework/python/lib/python3.7/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/var/ossec/framework/python/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/var/ossec/etc/ossec.conf'
```

Related issue https://github.com/wazuh/wazuh/issues/3335

Regards

**Comment by manuasir** [comment]
Done here https://github.com/wazuh/wazuh/pull/3352
