### ISSUE TITLE
[v4.0] Testing new images

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-docker#394]
Hi folks,

This issue is for tracking purposes.

### Purpose

The main goal is to test the integration of the new Wazuh Docker rework and the upcoming major version.

### Checks

- [x] Each environment variable behavior.
- [x] API / RBAC functionalities.
- [x] Active response.
- [x] Addition of new rules / CDB lists / decoders.
- [x] Wodle commands.
- [x] Localfile.
- [x] Syscollector.
- [x] Syscheck.
- [x] Autoenrollment.

**Comment by Zenidd** [comment]
Hi team,

**After deploying the wazuh-docker environment with Wazuh manager rc4 package, Kibana throws the following error during the initial WUI checks:**

![image](https://user-images.githubusercontent.com/14923294/96280049-c6a4b380-0fd7-11eb-89ac-74fb07b2425b.png)


**Then, after using the `Go to APP` button, the API has state `connected`:**

![image](https://user-images.githubusercontent.com/14923294/96280458-46cb1900-0fd8-11eb-8a96-8f938d4664a0.png)


**Clicking multiple times on the update button leads to different errors:**

![image](https://user-images.githubusercontent.com/14923294/96280697-94e01c80-0fd8-11eb-994e-42add515cab7.png)


**The related API errors are logged in manager `/var/ossec/logs/api.log`**

```
2020/10/16 15:53:45 INFO: unknown_user 172.21.0.4 "GET /security/user/authenticate" done in 43.000000001484295ms: 500
2020/10/16 15:53:45 INFO: wazuh 172.21.0.4 "GET /security/user/authenticate" done in 215.00000000014552ms: 200
2020/10/16 15:53:45 INFO: wazuh 172.21.0.4 "GET /manager/info" done in 42.00000000128057ms: 200
2020/10/16 15:53:45 INFO: wazuh 172.21.0.4 "GET /agents" done in 43.99999999805004ms: 200
2020/10/16 15:53:45 INFO: wazuh 172.21.0.4 "GET /cluster/status" done in 148.00000000104774ms: 200
2020/10/16 15:53:45 INFO: wazuh 172.21.0.4 "GET /security/user/authenticate" done in 235.99999999714782ms: 200
2020/10/16 15:53:45 INFO: wazuh 172.21.0.4 "GET /manager/info" done in 43.000000001484295ms: 200
2020/10/16 15:53:45 INFO: wazuh 172.21.0.4 "GET /agents" done in 43.99999999805004ms: 200
2020/10/16 15:53:45 INFO: wazuh 172.21.0.4 "GET /cluster/status" done in 43.000000001484295ms: 200
2020/10/16 15:53:46 INFO: wazuh 172.21.0.4 "GET /security/user/authenticate" done in 363.00000000119326ms: 200
2020/10/16 15:53:46 ERROR: Error executing API request locally: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140080157030144 and this is thread id 140080674723584.
[SQL: SELECT users.id AS users_id, users.username AS users_username, users.password AS users_password, users.allow_run_as AS users_allow_run_as, users.created_at AS users_created_at 
FROM users 
WHERE users.username = ?
 LIMIT ? OFFSET ?]
[parameters: [immutabledict({})]]
(Background on this error at: http://sqlalche.me/e/f405)
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1173, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 768, in _init_compiled
    self.cursor = self.create_cursor()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 1122, in create_cursor
    return self._dbapi_connection.cursor()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 965, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140080157030144 and this is thread id 140080674723584.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 231, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/var/ossec/framework/python/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 205, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/api-4.0.0-py3.8.egg/api/authentication.py", line 179, in check_token
    user = am.get_user(username=username)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/rbac/orm.py", line 784, in get_user
    return self.session.query(User).filter_by(username=username).first().to_dict()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1175, in _execute_context
    self._handle_dbapi_exception(
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1173, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 768, in _init_compiled
    self.cursor = self.create_cursor()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 1122, in create_cursor
    return self._dbapi_connection.cursor()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 965, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140080157030144 and this is thread id 140080674723584.
[SQL: SELECT users.id AS users_id, users.username AS users_username, users.password AS users_password, users.allow_run_as AS users_allow_run_as, users.created_at AS users_created_at 
FROM users 
WHERE users.username = ?
 LIMIT ? OFFSET ?]
[parameters: [immutabledict({})]]
(Background on this error at: http://sqlalche.me/e/f405)
2020/10/16 15:53:46 INFO: unknown_user 172.21.0.4 "GET /manager/info" done in 55.00000000029104ms: 500
2020/10/16 15:53:46 INFO: wazuh 172.21.0.4 "GET /security/user/authenticate" done in 226.99999999895226ms: 200
2020/10/16 15:53:46 INFO: wazuh 172.21.0.4 "GET /manager/info" done in 42.99999999784632ms: 200
2020/10/16 15:53:46 INFO: wazuh 172.21.0.4 "GET /agents" done in 45.00000000189175ms: 200
2020/10/16 15:53:46 INFO: wazuh 172.21.0.4 "GET /cluster/status" done in 45.9999999984575ms: 200
```

Greetings,

JP

**Comment by Zenidd** [comment]
Related to **Each environment variable behavior** check:

Different combinations of env variables have been tested for the Kibana container. They have not been traduced to its related configuration options in the `wazuh.yml` file. i.e:
```
    CHECKS_API=false
    EXTENSIONS_PCI=false 
    EXTENSIONS_GDPR=false 
    EXTENSIONS_AUDIT=false 
    EXTENSIONS_OSCAP=false 
    EXTENSIONS_CISCAT=false 
    EXTENSIONS_AWS=true 
    EXTENSIONS_VIRUSTOTAL=false 
    EXTENSIONS_OSQUERY=true 
```

After using these env, there were no related entries on the `wazuh.yml` file.

Greetings,

JP

**Comment by Zenidd** [comment]
Hi team,

The API errors described above were fixed and now both the WUI initial checks and the API refresh work without issues.
![image](https://user-images.githubusercontent.com/14923294/96424260-c33d4200-11fa-11eb-87fa-a749429bc674.png)


Greetings,

JP

**Comment by Zenidd** [comment]
###  API / RBAC functionalities - OK
- **OK** -  Initial API checks
- **OK** - Refresh API state
- **OK** - `GET /agents?status=active`
- **OK** - `GET /manager/info`
- **OK** - `GET /syscollector/000/packages?search=ssh&limit=1`
- **OK** - `GET /agents/000/config/logcollector/localfile`
- **OK** - `GET /agents/000/config/syscheck/syscheck`
- **OK** - `GET /agents/000/config/syscheck/rootcheck`
- **OK** - `GET /agents/000/config/wmodules/wmodules`
- **OK** - `GET /security/users/me`
- **OK** - `GET /security/roles`
- **OK** - GET /syscheck/000
- **OK** - Creating new API user
```
   POST /security/users
   {
   "username": "test_user",
   "password": "Change_me0",
   "allow_run_as": false
   }
```
- **OK** - Assign role to user 
```
   POST /security/users/100/roles?role_ids=1
```

**Comment by xr09** [comment]
> Related to **Each environment variable behavior** check:
> 
> Different combinations of env variables have been tested for the Kibana container. They have not been traduced to its related configuration options in the `wazuh.yml` file. i.e:
> 
> ```
>     CHECKS_API=false
>     EXTENSIONS_PCI=false 
>     EXTENSIONS_GDPR=false 
>     EXTENSIONS_AUDIT=false 
>     EXTENSIONS_OSCAP=false 
>     EXTENSIONS_CISCAT=false 
>     EXTENSIONS_AWS=true 
>     EXTENSIONS_VIRUSTOTAL=false 
>     EXTENSIONS_OSQUERY=true 
> ```
> 
> After using these env, there were no related entries on the `wazuh.yml` file.
> 
> Greetings,
> 
> JP

This is fixed in the last commit, we're using a config template (taken from [here](https://github.com/wazuh/wazuh-kibana-app/blob/4.0-7.9/server/lib/initial-wazuh-config.js)) without enabled defaults and the app [config](https://github.com/wazuh/wazuh-docker/blob/4.0/kibana-opendistro/config/wazuh_app_config.sh#L11-L36) will do the rest.
