### ISSUE TITLE
Can't update agents with Wazuh 4.1.0

### ISSUE THREAD

**Issue by cleverer** [wazuh/wazuh-docker#443]
Using the api I get the following response and error in the api.log:

```json
{
  "error": "3013",
  "message": {
    "title": "Wazuh Internal Error",
    "detail": "Wazuh Internal Error",
    "remediation": "Please, check `WAZUH_HOME/logs/ossec.log`, `WAZUH_HOME/logs/cluster.log` and `WAZUH_HOME/logs/api.log` to get more information about the error",
    "dapi_errors": {
      "manager": {
        "error": "Unable to connect with socket: [Errno 2] No such file or directory",
        "logfile": "WAZUH_HOME/logs/api.log"
      }
    },
    "error": 1000
  }
}
```

```python
2021/02/18 13:50:26 ERROR: Error executing API request locally: Error 1013 - Unable to connect with socket: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/wazuh_socket.py", line 27, in _connect
    self.s.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 250, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/var/ossec/framework/python/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 224, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/rbac/decorators.py", line 417, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/agent.py", line 737, in upgrade_agents
    core_upgrade_agents(command='upgrade' if not (installer or file_path) else 'upgrade_custom',
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/agent.py", line 1261, in core_upgrade_agents
    s = OssecSocket(common.UPGRADE_SOCKET)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/wazuh_socket.py", line 22, in __init__
    self._connect()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/wazuh_socket.py", line 29, in _connect
    raise WazuhException(1013, str(e))
wazuh.core.exception.WazuhException: Error 1013 - Unable to connect with socket: [Errno 2] No such file or directory
2021/02/18 13:50:26 INFO: acme-user 172.28.0.7 "PUT /agents/upgrade" done in 0.066s: 500
```

Using the `agent_upgrade` command leads to a simliar error:

```python
Error executing API request locally: Error 1013 - Unable to connect with socket: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/wazuh_socket.py", line 27, in _connect
    self.s.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 250, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/var/ossec/framework/python/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 224, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/rbac/decorators.py", line 417, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/agent.py", line 737, in upgrade_agents
    core_upgrade_agents(command='upgrade' if not (installer or file_path) else 'upgrade_custom',
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/agent.py", line 1261, in core_upgrade_agents
    s = OssecSocket(common.UPGRADE_SOCKET)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/wazuh_socket.py", line 22, in __init__
    self._connect()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/wazuh_socket.py", line 29, in _connect
    raise WazuhException(1013, str(e))
wazuh.core.exception.WazuhException: Error 1013 - Unable to connect with socket: [Errno 2] No such file or directory
Internal error: 
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 220, in <module>
    main()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 186, in main
    result = send_command(function=upgrade_agents, command=create_command())
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 115, in send_command
    return raise_if_exc(pool.submit(run, dapi.distribute_function()).result())
  File "/var/ossec/framework/python/lib/python3.8/site-packages/api-4.1.0-py3.8.egg/api/util.py", line 294, in raise_if_exc
    _create_problem(obj)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/api-4.1.0-py3.8.egg/api/util.py", line 264, in _create_problem
    raise ProblemException(status=500 if not code else code, type=exc.type, title=exc.title, detail=exc.message,
connexion.exceptions.ProblemException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 227, in <module>
    if args.debug:
AttributeError: 'Namespace' object has no attribute 'debug'
```

**Comment by npdgm** [comment]
Hi @cleverer
We experienced the same error and I summited PR #447.
You could fix it running inside wazuh-manager containers :
`install -d -m 0770 -o ossec -g ossec /var/ossec/queue/tasks`
Then `/var/ossec/queue/tasks/tasks.db` should be created after a few minutes, or restart the thing.
Cheers

**Comment by cleverer** [comment]
Cool thanks!

Had to run it in both `wazuh-manager` and `wazuh-worker`-containers but it indeed worked!
