### ISSUE TITLE
Docker container with kibana won't start

### ISSUE THREAD

**Issue by d-malko** [wazuh/wazuh-docker#444]
Hello team!
I tested Wazuh as a standalone instance, but want to start it in docker.
I cloned git repo and I am trying to start Wazuh in docker for production from branch 4.1.0

```
git clone https://github.com/wazuh/wazuh-docker.git -b v4.1.0 --depth=1
docker-compose -f generate-opendistro-certs.yml run --rm generator
docker-compose -f production-cluster.yml up -d
```

For testing I left `ssl_certs/certs.yml` intact.
```
ca:
   root:
      dn: CN=root-ca,OU=CA,O=Example\, Inc.,DC=example,DC=com
      pkPassword: none
      keysize: 2048
      file: root-ca.pem
   intermediate:
      dn: CN=intermediate,OU=CA,O=Example\, Inc.,DC=example,DC=com
      keysize: 2048
      validityDays: 3650
      pkPassword: intermediate-ca-password
      file: intermediate-ca.pem

nodes:
  - name: node1
    dn: CN=node1,OU=Ops,O=Example\, Inc.,DC=example,DC=com
    dns:
      - elasticsearch
  - name: node2
    dn: CN=node2,OU=Ops,O=Example\, Inc.,DC=example,DC=com
    dns:
      - elasticsearch-2
  - name: node3
    dn: CN=node3,OU=Ops,O=Example\, Inc.,DC=example,DC=com
    dns:
      - elasticsearch-3
  - name: filebeat
    dn: CN=filebeat,OU=Ops,O=Example\, Inc.,DC=example,DC=com
    dns:
      - wazuh
``` 

But Kibana keep falling with the exception

```
kibana_1           | {
kibana_1           |   "name" : "elasticsearch",
kibana_1           |   "cluster_name" : "wazuh-cluster",
kibana_1           |   "cluster_uuid" : "qOpK-FddT0uB1iMnod_0Iw",
kibana_1           |   "version" : {
kibana_1           |     "number" : "7.10.0",
kibana_1           |     "build_flavor" : "oss",
kibana_1           |     "build_type" : "tar",
kibana_1           |     "build_hash" : "51e9d6f22758d0374a0f3f5c6e8f3a7997850f96",
kibana_1           |     "build_date" : "2020-11-09T21:30:33.964949Z",
kibana_1           |     "build_snapshot" : false,
kibana_1           |     "lucene_version" : "8.7.0",
kibana_1           |     "minimum_wire_compatibility_version" : "6.8.0",
kibana_1           |     "minimum_index_compatibility_version" : "6.0.0-beta1"
kibana_1           |   },
kibana_1           |   "tagline" : "You Know, for Search"
kibana_1           | }
kibana_1           | Elasticsearch is up.
kibana_1           | Wazuh alerts template not loaded - sleeping.
kibana_1           | Wazuh alerts template is loaded.
kibana_1           | Waiting for Kibana API. Sleeping 5 seconds
kibana_1           | Waiting for Kibana API. Sleeping 5 seconds
kibana_1           | {"type":"log","@timestamp":"2021-02-19T20:44:39Z","tags":["info","plugins-service"],"pid":58,"message":"Plugin \"telemetryManagementSection\" has been disabled since the following direct or transitive dependencies are missing or disabled: [telemetry]"}
kibana_1           | {"type":"log","@timestamp":"2021-02-19T20:44:39Z","tags":["info","plugins-service"],"pid":58,"message":"Plugin \"newsfeed\" is disabled."}
kibana_1           | {"type":"log","@timestamp":"2021-02-19T20:44:39Z","tags":["info","plugins-service"],"pid":58,"message":"Plugin \"telemetry\" is disabled."}
kibana_1           | {"type":"log","@timestamp":"2021-02-19T20:44:39Z","tags":["info","plugins-service"],"pid":58,"message":"Plugin \"visTypeXy\" is disabled."}
kibana_1           | {"type":"log","@timestamp":"2021-02-19T20:44:39Z","tags":["warning","config","deprecation"],"pid":58,"message":"\"cpu.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuPath\""}
kibana_1           | {"type":"log","@timestamp":"2021-02-19T20:44:39Z","tags":["warning","config","deprecation"],"pid":58,"message":"\"cpuacct.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuAcctPath\""}
kibana_1           | {"type":"log","@timestamp":"2021-02-19T20:44:39Z","tags":["warning","config","deprecation"],"pid":58,"message":"\"server.defaultRoute\" is deprecated and has been replaced by \"uiSettings.overrides.defaultRoute\""}
kibana_1           | {"type":"log","@timestamp":"2021-02-19T20:44:39Z","tags":["fatal","root"],"pid":58,"message":"{ Error: EISDIR: illegal operation on a directory, read\n    at Object.readSync (fs.js:498:3)\n    at tryReadSync (fs.js:332:20)\n    at readFileSync (fs.js:369:19)\n    at readFile (/usr/share/kibana/src/core/server/http/ssl_config.js:181:31)\n    at new SslConfig (/usr/share/kibana/src/core/server/http/ssl_config.js:131:18)\n    at new HttpConfig (/usr/share/kibana/src/core/server/http/http_config.js:175:16)\n    at MapSubscriber.HttpService.config$.pipe [as project] (/usr/share/kibana/src/core/server/http/http_service.js:61:177)\n    at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:49:35)\n    at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at CombineLatestSubscriber.notifyNext (/usr/share/kibana/node_modules/rxjs/internal/observable/combineLatest.js:97:34)\n    at InnerSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/InnerSubscriber.js:28:21)\n    at InnerSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at DistinctUntilChangedSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n    at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18) errno: -21, syscall: 'read', code: 'EISDIR' }"}
kibana_1           |
kibana_1           |  FATAL  Error: EISDIR: illegal operation on a directory, read
kibana_1           |
 ~/git/wazuh-prod/wazuh-docker
```

I thought this was the issue that I found in [this bug](https://discuss.elastic.co/t/kibana-7-9-0-configuring-logger-failed-error-eisdir-illegal-operation-on-a-directory-read/245653)
I build kibana-odfe image from your repo and change kibana-odfe/config/kibana_settings.sh file to remove path.data with sed
```
echo "REMOVING PATH DATA"
if grep -q 'path.data:' /usr/share/kibana/config/kibana.yml; then
    sed -i '/path.data:/d' /usr/share/kibana/config/kibana.yml
  fi
cat /usr/share/kibana/config/kibana.yml
```

```
REMOVING PATH DATA
kibana_1           | ---
kibana_1           | # Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
kibana_1           | #
kibana_1           | # Licensed under the Apache License, Version 2.0 (the "License").
kibana_1           | # You may not use this file except in compliance with the License.
kibana_1           | # A copy of the License is located at
kibana_1           | #
kibana_1           | #     http://www.apache.org/licenses/LICENSE-2.0
kibana_1           | #
kibana_1           | # or in the "license" file accompanying this file. This file is distributed
kibana_1           | # on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
kibana_1           | # express or implied. See the License for the specific language governing
kibana_1           | # permissions and limitations under the License.
kibana_1           |
kibana_1           | # Description:
kibana_1           | # Default Kibana configuration from kibana-docker.
kibana_1           |
kibana_1           | server.name: kibana
kibana_1           | server.host: "0"
kibana_1           | elasticsearch.hosts: https://elasticsearch:9200
kibana_1           | elasticsearch.ssl.verificationMode: none
kibana_1           | elasticsearch.username: kibanaserver
kibana_1           | elasticsearch.password: kibanaserver
kibana_1           | elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
kibana_1           |
kibana_1           | opendistro_security.multitenancy.enabled: true
kibana_1           | opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
kibana_1           | opendistro_security.readonly_mode.roles: ["kibana_read_only"]
kibana_1           |
kibana_1           | # Use this setting if you are running kibana without https
kibana_1           | opendistro_security.cookie.secure: false
kibana_1           |
kibana_1           | newsfeed.enabled: false
kibana_1           | telemetry.optIn: false
kibana_1           | telemetry.enabled: false
kibana_1           | security.showInsecureClusterWarning: false
kibana_1           | server.defaultRoute: /app/wazuh
```

But I've got the same error after all.
Please, I need your advice.
Thanks in advance.

**Comment by wisoez** [comment]
same issue :( 
![image](https://user-images.githubusercontent.com/10806362/108989072-c922c280-76c7-11eb-8ce9-4c2a3ddde5ac.png)

**Comment by nu11secur1ty** [comment]
The steps of reproduction which you use, please?
BR

**Comment by d-malko** [comment]
@nu11secur1ty Thank you for your answer! As I understand, the solution is to use the older 4.0 version?

**Comment by nu11secur1ty** [comment]
Yes my friend. BR

**Comment by alberpilot** [comment]
Hello @nu11secur1ty @d-malko @wisoez 

  I'm sorry for the late response. wazuh-docker v4.1.5 and all 4.x versions must work. The error you had usually means that it's trying to access a file but it found a folder. Could you please verify if your `production_cluster/kibana_ssl/` doesn't contain any folder called `cert.pem` or `key.pem`? In this location or other where you must have the certificates. If so, remove them and run again: `docker-compose -f generate-opendistro-certs.yml run --rm generator` and `bash production_cluster/kibana_ssl/generate-self-signed-cert.sh`. 

Hope it helps. 

Regards, 
Alberto R

**Comment by alberpilot** [comment]
I proceed to close this issue. Please don't hesitate to open it again if you have any doubt.
