### ISSUE TITLE
Permission denied kibana key when using docker production installation

### ISSUE THREAD

**Issue by abdul-elah-js** [wazuh/wazuh-docker#485]
I'm installing Wazuh using docker (production deployment) and I followed every step on this [page](https://documentation.wazuh.com/current/docker/wazuh-container.html) and for some reason I'm getting this error
`FATAL  Error: EACCES: permission denied, open '/usr/share/kibana/config/key.pem'`

**OS**:
`Ubuntu 18.04.5 LTS (bionic)`
**Docker**
`version 20.10.7, build f0df350`
**Docker Compose**
`version 1.17.1`

Logs after running the `docker-compose -f production-cluster.yml up` command

```
kibana_1           | Wazuh alerts template not loaded - sleeping.
kibana_1           | Wazuh alerts template is loaded.
kibana_1           | Wazuh APP already configured
kibana_1           | Waiting for Kibana API. Sleeping 5 seconds
kibana_1           | Waiting for Kibana API. Sleeping 5 seconds
kibana_1           | {"type":"log","@timestamp":"2021-06-22T14:58:34Z","tags":["info","plugins-service"],"pid":25,"message":"Plugin \"telemetryManagementSection\" has been disabled since the following direct or transitive dependencies are missing or disabled: [telemetry]"}
kibana_1           | {"type":"log","@timestamp":"2021-06-22T14:58:34Z","tags":["info","plugins-service"],"pid":25,"message":"Plugin \"newsfeed\" is disabled."}
kibana_1           | {"type":"log","@timestamp":"2021-06-22T14:58:34Z","tags":["info","plugins-service"],"pid":25,"message":"Plugin \"telemetry\" is disabled."}
kibana_1           | {"type":"log","@timestamp":"2021-06-22T14:58:34Z","tags":["info","plugins-service"],"pid":25,"message":"Plugin \"visTypeXy\" is disabled."}
kibana_1           | {"type":"log","@timestamp":"2021-06-22T14:58:34Z","tags":["warning","config","deprecation"],"pid":25,"message":"\"cpu.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuPath\""}
kibana_1           | {"type":"log","@timestamp":"2021-06-22T14:58:34Z","tags":["warning","config","deprecation"],"pid":25,"message":"\"cpuacct.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuAcctPath\""}
kibana_1           | {"type":"log","@timestamp":"2021-06-22T14:58:34Z","tags":["warning","config","deprecation"],"pid":25,"message":"\"server.defaultRoute\" is deprecated and has been replaced by \"uiSettings.overrides.defaultRoute\""}
kibana_1           | {"type":"log","@timestamp":"2021-06-22T14:58:34Z","tags":["fatal","root"],"pid":25,"message":"{ Error: EACCES: permission denied, open '/usr/share/kibana/config/key.pem'\n    at Object.openSync (fs.js:443:3)\n    at readFileSync (fs.js:343:35)\n    at readFile (/usr/share/kibana/src/core/server/http/ssl_config.js:181:31)\n    at new SslConfig (/usr/share/kibana/src/core/server/http/ssl_config.js:131:18)\n    at new HttpConfig (/usr/share/kibana/src/core/server/http/http_config.js:175:16)\n    at MapSubscriber.HttpService.config$.pipe [as project] (/usr/share/kibana/src/core/server/http/http_service.js:61:177)\n    at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:49:35)\n    at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at CombineLatestSubscriber.notifyNext (/usr/share/kibana/node_modules/rxjs/internal/observable/combineLatest.js:97:34)\n    at InnerSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/InnerSubscriber.js:28:21)\n    at InnerSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at DistinctUntilChangedSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n    at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:55:26)\n  errno: -13,\n  syscall: 'open',\n  code: 'EACCES',\n  path: '/usr/share/kibana/config/key.pem' }"}
kibana_1           | 
kibana_1           |  FATAL  Error: EACCES: permission denied, open '/usr/share/kibana/config/key.pem'
kibana_1           | 
kibana_1           |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
kibana_1           |                                  Dload  Upload   Total   Spent    Left  Speed
kibana_1           | {
kibana_1           |   "name" : "elasticsearch",
kibana_1           |   "cluster_name" : "wazuh-cluster",
kibana_1           |   "cluster_uuid" : "g0Uhyv2eTlad5tD_1maCCg",
kibana_1           |   "version" : {
kibana_1           |     "number" : "7.10.2",
kibana_1           |     "build_flavor" : "oss",
kibana_1           |     "build_type" : "tar",
kibana_1           |     "build_hash" : "747e1cc71def077253878a59143c1f785afa92b9",
kibana_1           |     "build_date" : "2021-01-13T00:42:12.435326Z",
kibana_1           |     "build_snapshot" : false,
kibana_1           |     "lucene_version" : "8.7.0",
kibana_1           |     "minimum_wire_compatibility_version" : "6.8.0",
kibana_1           |     "minimum_index_compatibility_version" : "6.0.0-beta1"
kibana_1           |   },
kibana_1           |   "tagline" : "You Know, for Search"
kibana_1           | }
100   535  100   535    0     0   2917      0 --:--:-- --:--:-- --:--:--  2923
kibana_1           | Elasticsearch is up.
```

**Comment by abdul-elah-js** [comment]
Solved by changing permission for the certificate, for some reason the `key.pem` certificate was generated with permission `600` instead of `644`
