### ISSUE TITLE
Error creating Wazuh Manager cluster

### ISSUE THREAD

**Issue by vcerenu** [wazuh/wazuh-docker#574]
A test of setting up a cluster with 1 master node and 1 worker node of Wazuh manager 4.3.0 was performed and I got the following error:

```
cont-init.d] 2-manager: executing... 
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: users

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/scripts/create_user.py", line 69, in <module>
    initial_users = db_users()
  File "/var/ossec/framework/scripts/create_user.py", line 35, in db_users
    users_result = get_users()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/rbac/decorators.py", line 386, in wrapper
    allow = _match_permissions(req_permissions=req_permissions, rbac_mode=rbac.get()['rbac_mode'])
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/rbac/decorators.py", line 232, in _match_permissions
    rbac_mode == 'black' and _black_expansion(req_resources, allow_match)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/rbac/decorators.py", line 146, in _black_expansion
    expanded_resource = _expand_resource(chunk)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/rbac/decorators.py", line 57, in _expand_resource
    users = auth.get_users()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/rbac/orm.py", line 851, in get_users
    users = self.session.query(User).all()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3211, in all
    return list(self)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: users
[SQL: SELECT users.id AS users_id, users.username AS users_username, users.password AS users_password, users.allow_run_as AS users_allow_run_as, users.created_at AS users_created_at 
FROM users]
(Background on this error at: http://sqlalche.me/e/e3q8)
There was an error configuring the API user
[cont-init.d] 2-manager: exited 0.
[cont-init.d] done.
[services.d] starting services
[cont-finish.d] executing container finish scripts...
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: unable to subscribe to events for /var/run/s6/services/ossec-logs: No such file or directory
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

These tests were performed with the[ test-cluster.yaml](https://github.com/wazuh/wazuh-docker/blob/new-packages-release/test-cluster.yml) script from the [new-packages-release](https://github.com/wazuh/wazuh-docker/tree/new-packages-release)s branch of this repository. This is the cluster configuration in Docker Compose:

```
  wazuh.master:
    image: wazuh/wazuh-odfe:4.3.0
    hostname: wazuh.master
    restart: always
    ports:
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - ELASTICSEARCH_URL=https://wazuh1.indexer:9700
      - ELASTIC_USERNAME=admin
      - ELASTIC_PASSWORD=admin
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=acme-user
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - ossec-api-configuration:/var/ossec/api/configuration
      - ossec-etc:/var/ossec/etc
      - ossec-logs:/var/ossec/logs
      - ossec-queue:/var/ossec/queue
      - ossec-var-multigroups:/var/ossec/var/multigroups
      - ossec-integrations:/var/ossec/integrations
      - ossec-active-response:/var/ossec/active-response/bin
      - ossec-agentless:/var/ossec/agentless
      - ossec-wodles:/var/ossec/wodles
      - filebeat-etc:/etc/filebeat
      - filebeat-var:/var/lib/filebeat
      - ./production_cluster/wazuh_indexer_ssl_certs/root-ca.pem:/etc/ssl/root-ca.pem
      - ./production_cluster/wazuh_indexer_ssl_certs/wazuh.master.pem:/etc/ssl/filebeat.pem
      - ./production_cluster/wazuh_indexer_ssl_certs/wazuh.master-key.pem:/etc/ssl/filebeat.key
      - ./production_cluster/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf

  wazuh.worker:
    image: wazuh/wazuh-odfe:4.3.0
    hostname: wazuh.worker
    restart: always
    environment:
      - ELASTICSEARCH_URL=https://wazuh1.indexer:9700
      - ELASTIC_USERNAME=admin
      - ELASTIC_PASSWORD=admin
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
    volumes:
      - worker-ossec-api-configuration:/var/ossec/api/configuration
      - worker-ossec-etc:/var/ossec/etc
      - worker-ossec-logs:/var/ossec/logs
      - worker-ossec-queue:/var/ossec/queue
      - worker-ossec-var-multigroups:/var/ossec/var/multigroups
      - worker-ossec-integrations:/var/ossec/integrations
      - worker-ossec-active-response:/var/ossec/active-response/bin
      - worker-ossec-agentless:/var/ossec/agentless
      - worker-ossec-wodles:/var/ossec/wodles
      - worker-filebeat-etc:/etc/filebeat
      - worker-filebeat-var:/var/lib/filebeat
      - ./production_cluster/wazuh_indexer_ssl_certs/root-ca.pem:/etc/ssl/root-ca.pem
      - ./production_cluster/wazuh_indexer_ssl_certs/wazuh.worker.pem:/etc/ssl/filebeat.pem
      - ./production_cluster/wazuh_indexer_ssl_certs/wazuh.worker-key.pem:/etc/ssl/filebeat.key
      - ./production_cluster/wazuh_cluster/wazuh_worker.conf:/wazuh-config-mount/etc/ossec.conf
```

**Comment by vcerenu** [comment]
The stack assembly was being tested within the [test_cluster.yml](https://github.com/wazuh/wazuh-docker/blob/new-packages-release/test-cluster.yml) script, which I have found some problems:

An error was found in the wazuh-manager cluster startup, which is assigned to the corresponding team in issue [574](https://github.com/wazuh/wazuh-docker/issues/574).

Because version 4.3.0 rc3 had the error at startup, we tried to start the cluster with the 4.3.0 rc1 image, but apparently there are some differences in the templates:
```
wazuh3.indexer_1   | [2022-02-08T20:20:22,398][INFO ][o.o.a.b.TransportShardBulkAction] [wazuh3.indexer] [wazuh-alerts-4.x-2022.02.08][0] mapping update rejected by primary
wazuh3.indexer_1   | java.lang.IllegalArgumentException: mapper [decoder.name] cannot be changed from type [keyword] to [text]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.ParametrizedFieldMapper.merge(ParametrizedFieldMapper.java:110) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.ParametrizedFieldMapper.merge(ParametrizedFieldMapper.java:74) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:585) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:544) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:571) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.RootObjectMapper.doMerge(RootObjectMapper.java:330) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:544) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.RootObjectMapper.merge(RootObjectMapper.java:325) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.Mapping.merge(Mapping.java:127) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:306) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.MapperService.internalMerge(MapperService.java:567) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.MapperService.internalMerge(MapperService.java:512) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.index.mapper.MapperService.merge(MapperService.java:453) ~[opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:372) [opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:212) [opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:276) [opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:165) [opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:98) [opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.action.support.replication.TransportWriteAction$1.doRun(TransportWriteAction.java:220) [opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:792) [opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [opensearch-1.2.3.jar:1.2.3]
wazuh3.indexer_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
wazuh3.indexer_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
wazuh3.indexer_1   | 	at java.lang.Thread.run(Thread.java:832) [?:?]

```

Check connection between wazuh-dashboard and wazuh-indexer. The indexer cluster starts correctly but from the dashboard I get the following error:

```
wazuh.dashboard_1  | {"type":"log","@timestamp":"2022-02-08T19:20:37Z","tags":["error","opensearch","data"],"pid":11,"message":"[ConnectionError]: getaddrinfo ENOTFOUND wazuh1-indexer wazuh1-indexer:9700"}
wazuh.dashboard_1  | {"type":"log","@timestamp":"2022-02-08T19:20:40Z","tags":["error","opensearch","data"],"pid":11,"message":"[ConnectionError]: getaddrinfo ENOTFOUND wazuh1-indexer wazuh1-indexer:9700"}
wazuh.dashboard_1  | {"type":"log","@timestamp":"2022-02-08T19:20:42Z","tags":["error","opensearch","data"],"pid":11,"message":"[ConnectionError]: getaddrinfo ENOTFOUND wazuh1-indexer wazuh1-indexer:9700"}
wazuh.dashboard_1  | {"type":"log","@timestamp":"2022-02-08T19:20:45Z","tags":["error","opensearch","data"],"pid":11,"message":"[ConnectionError]: getaddrinfo ENOTFOUND wazuh1-indexer wazuh1-indexer:9700"}
wazuh.dashboard_1  | {"type":"log","@timestamp":"2022-02-08T19:20:47Z","tags":["error","opensearch","data"],"pid":11,"message":"[ConnectionError]: getaddrinfo ENOTFOUND wazuh1-indexer wazuh1-indexer:9700"}
wazuh.dashboard_1  | {"type":"log","@timestamp":"2022-02-08T19:20:50Z","tags":["error","opensearch","data"],"pid":11,"message":"[ConnectionError]: getaddrinfo ENOTFOUND wazuh1-indexer wazuh1-indexer:9700"}

```

The connection from the dashboard container to indexer was checked and it works correctly, so we continue to check its SSL configuration:

```
uid=0(root) gid=0(root) groups=0(root)
root@wazuh:/# uname -a
Linux wazuh.dashboard 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
root@wazuh:/# curl -k -u admin:SecretPassword https://wazuh1.indexer:9700/_cat/nodes?v
ip         heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
172.28.0.5           45          98  25    2.44    1.13     0.47 dimr      -      wazuh2.indexer
172.28.0.3           25          98  25    2.44    1.13     0.47 dimr      *      wazuh1.indexer
172.28.0.4           41          98  26    2.44    1.13     0.47 dimr      -      wazuh3.indexer
root@wazuh:/# 
```
