### ISSUE TITLE
Install 4.3 into centos 7 host

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-docker#636]
When proceeding to install version 4.3 with docker on a centos 7 host, it does not start due to the following error:
```
wazuh.dashboard_1 | {"type":"log","@timestamp":"2022-05-11T23:05:01Z","tags":["fatal","root"],"pid":9,"message": "{ Error: listen EACCES: permission denied 0.0.0.0:443\n at Server.setupListenHandle [as _listen2] (net.js:1263:19)\n at listenInCluster (net.js:1328:12)\n at doListen (net.js:1461:7)\n at process._tickCallback (internal/process/next_tick.js:63:19)\n code: 'EACCES',\n errno: 'EACCES',\n syscall: 'listen ',\n address: '0.0.0.0',\n port: 443 }"}
wazuh.dashboard_1 |
wazuh.dashboard_1 | FATAL Error: listen EACCES: permission denied 0.0.0.0:443
wazuh.dashboard_1 |
```
This is because on some systems non-root users are not allowed to publish ports less than 1024.
Previously we had an Nginx reverse proxy that did have permissions to publish these ports.

**Comment by alberpilot** [comment]
Solved here: https://github.com/wazuh/wazuh-docker/pull/637
