### ISSUE TITLE
Cant configure LDAP Wazuh 4.3.4 Docker

### ISSUE THREAD

**Issue by xBounceIT** [wazuh/wazuh-docker#675]
Hi,

im trying to configure LDAP on Wazuh Indexer 4.3.4 bu the securityadmin.sh script fails to execute. This is the error:
Security Admin v7
Will connect to wazuh1.indexer:9300 ... done
ERR: Cannot connect to OpenSearch. Please refer to opensearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{U6oXjIVpTnahdgOI5Fq5kA}{wazuh1.indexer}{172.29.0.4:9300}]]
        at org.opensearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:381)
        at org.opensearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:272)
        at org.opensearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:79)
        at org.opensearch.client.transport.TransportClient.doExecute(TransportClient.java:484)
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:433)
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:419)
        at org.opensearch.security.tools.SecurityAdmin.execute(SecurityAdmin.java:524)
        at org.opensearch.security.tools.SecurityAdmin.main(SecurityAdmin.java:157)

For better context, these are two threads that i have created on the forum looking for a fix.
https://groups.google.com/g/wazuh/c/Ol5sEcvzGH8/m/Nu4Mh8IlBQAJ
https://groups.google.com/g/wazuh/c/c9LOjHHppCg/m/CNHGuoYWBQAJ

Best regards,
Daniel D.

**Comment by xBounceIT** [comment]
This is the command that i execute to run the securityadmin.sh:

docker exec -it multi-node_wazuh1.indexer_1 /bin/bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -cacert /usr/share/wazuh-indexer/config/certs/root-ca.pem -cert /usr/share/wazuh-indexer/config/certs/admin.pem -key /usr/share/wazuh-indexer/config/certs/admin-key.pem -h wazuh1.indexer

**Comment by vcerenu** [comment]
Hello @xBounceIT 

Is the 4.3.4 deployment you are doing single node or multi node?
I ask you to attach the errors that are generated in the Wazuh indexer log

tail -500 /var/log/opensearch/<node_name>.log

Also if you can attach the opensearch.yml file that you are using to start Wazuh indexer

**Comment by xBounceIT** [comment]
Hi,

im using the multi-node deployment.

The path you are asking does not exist, but i imagined you meant /var/log/wazuh-indexer/wazuh-cluster.log. I've attached the outpu
[output.txt](https://github.com/wazuh/wazuh-docker/files/8954976/output.txt)
t of the command.

**Comment by vcerenu** [comment]
Are you using our scripts to deploy the multi node cluster? if you made modifications I ask you if you can send me those changes, removing any confidential information from your environment, also send me the opensearch.yml files of each of the nodes to review the configuration.

**Comment by xBounceIT** [comment]
Im not using any script, i cloned the repo from github as the Official Documentation describes, then i put up the containers by doing a docker-compose up -d

This is the opensearch.yml of the first node, i didnt touch anything:

network.host: wazuh1.indexer
node.name: wazuh1.indexer
cluster.initial_master_nodes:
        - wazuh1.indexer
        - wazuh2.indexer
        - wazuh3.indexer
cluster.name: "wazuh-cluster"
discovery.seed_hosts:
        - wazuh1.indexer
        - wazuh2.indexer
        - wazuh3.indexer
node.max_local_storage_nodes: "3"
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer
plugins.security.ssl.http.pemcert_filepath: ${OPENSEARCH_PATH_CONF}/certs/wazuh1.indexer.pem
plugins.security.ssl.http.pemkey_filepath: ${OPENSEARCH_PATH_CONF}/certs/wazuh1.indexer.key
plugins.security.ssl.http.pemtrustedcas_filepath: ${OPENSEARCH_PATH_CONF}/certs/root-ca.pem
plugins.security.ssl.transport.pemcert_filepath: ${OPENSEARCH_PATH_CONF}/certs/wazuh1.indexer.pem
plugins.security.ssl.transport.pemkey_filepath: ${OPENSEARCH_PATH_CONF}/certs/wazuh1.indexer.key
plugins.security.ssl.transport.pemtrustedcas_filepath: ${OPENSEARCH_PATH_CONF}/certs/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false
plugins.security.authcz.admin_dn:
- "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
- "CN=wazuh1.indexer,OU=Wazuh,O=Wazuh,L=California,C=US"
- "CN=wazuh2.indexer,OU=Wazuh,O=Wazuh,L=California,C=US"
- "CN=wazuh3.indexer,OU=Wazuh,O=Wazuh,L=California,C=US"
- "CN=filebeat,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.restapi.roles_enabled:
- "all_access"
- "security_rest_api_access"
plugins.security.allow_default_init_securityindex: true
cluster.routing.allocation.disk.threshold_enabled: false
compatibility.override_main_response_version: true
