### ISSUE TITLE
The default password can't be changed

### ISSUE THREAD

**Issue by jesse-zhangh** [wazuh/wazuh-docker#712]
**Env:** 
AWS EC2 
**docker info:**
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:46 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:00:51 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.7
  GitCommit:        0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc:
  Version:          1.1.3
  GitCommit:        v1.1.3-0-g6724737
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**docker-compose info:**
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Wazuh version:** 
4.3.6

**Change Method 1**
```
$ sudo docker run --rm -ti wazuh/wazuh-indexer:4.3.6 bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh
This script must be run as root.
```

**Change Method 2**
Entry the docker and execute the script:
```
$ sudo docker exec -it single-node_wazuh.indexer_1 bash
wazuh-indexer@wazuh:~$ cd plugins/opensearch-security/tools/
wazuh-indexer@wazuh:~/plugins/opensearch-security/tools$ bash wazuh-passwords-tool.sh 
This script must be run as root.
```

**Change Method 3**
Before deployment, I change the default password in configuration files, including:
docker-compose.yml
config/wazuh_indexer/internal_users.yml
config/wazuh_dashboard/wazuh.yml
The password to be changed is the same among different files.
After deployment, the api doesn't run.

**Change Method 4**
Before deployment, I only change the admin password in docker-compose.yml and internal_users.yml.
But it is an error reporting that no template found for the selected index pattern.
I handle the error but template doesn't work fine and there is no info on each modules.

How can i change the default password ?
Thank you. Looking forward to your reply.

**Comment by rauldpm** [comment]
Hello

We are currently working to incorporate this procedure into the documentation, which is in the process of being reviewed and will be released shortly.

Meanwhile, the procedure would be as follows:

1. From the machine hosting the docker containers, run this to generate the hash of the new password. 

```
docker run --rm -ti wazuh/wazuh-indexer:4.3.6 bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh
```

2. Take for example we are using single-node deployment. Copy the hash and replace it with the admin user here: `/single-node/config/wazuh_indexer/internal_users.yml`
3. Change the default `INDEXER_PASSWORD` in the `docker-compose.yml` file to the new one. Search and replace it.
5. Start the stack: `docker-compose up -d`
6. Do `docker ps` and note the name of the Wazuh indexer container.
7. Run `docker exec -it INDEXER_CONTAINER_NAME bash` to enter the container
8. Set the following variables

```
export INSTALLATION_DIR=/usr/share/wazuh-indexer
export OPENSEARCH_PATH_CONF=${INSTALLATION_DIR}/config
CACERT=$OPENSEARCH_PATH_CONF/certs/root-ca.pem
KEY=$OPENSEARCH_PATH_CONF/certs/admin-key.pem
CERT=$OPENSEARCH_PATH_CONF/certs/admin.pem
export JAVA_HOME=/usr/share/wazuh-indexer/jdk
```

7. Run this command 

```
bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -cd /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/ -nhnv -cacert  $CACERT -cert $CERT -key $KEY -p 9300 -icl
```

8. Login in with the new password

**Comment by jesse-zhangh** [comment]
hello @rauldpm 
Thank you very much. 
I succeeded. 
At the same time, I would like to ask whether the password change of other accounts such as Kibanaserver and Waziuh-wui is similar to this process?

**Comment by rauldpm** [comment]
Sorry for the late reply, depending on the case it may vary at some point

For user wazuh-wui:


- Modify API_PASSWORD to your desired password in docker-compose.yml
- Modify the password value in the file `single-node/config/wazuh-dashboard/wazuh.yml` file with the password you set in API_PASSWORD of docker-compose.yml file
- Start the stack
  - docker-compose up -d
  
  
For other users:

- Generate the hash with the password you want

```
docker run --rm -ti wazuh/wazuh-indexer:4.3.6 bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh
```

- Modify the single-node/confg/wazuh-indexer/internal-users.yml` file with the generated hash
- If you are changing the password of the kibanaserver user, do the following, otherwise skip it:
  - Add in the environment section of Wazuh dashboard, the following:
    - DASHBOARD_USERNAME=kibanaserver
    - DASHBOARD_PASSWORD=password_of_generated_hash

- Start the stack
 - `docker-compose up -d`

- Access the wazuh indexer container `docker exec -it single-node_wazuh.indexer_1 bash`

- Set the following variables

```
export INSTALLATION_DIR=/usr/share/wazuh-indexer
export OPENSEARCH_PATH_CONF=${INSTALLATION_DIR}/config
CACERT=$OPENSEARCH_PATH_CONF/certs/root-ca.pem
KEY=$OPENSEARCH_PATH_CONF/certs/admin-key.pem
CERT=$OPENSEARCH_PATH_CONF/certs/admin.pem
export JAVA_HOME=/usr/share/wazuh-indexer/jdk
```

- Apply changes

```
bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -cd /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/ -nhnv -cacert  $CACERT -cert $CERT -key $KEY -p 9300 -icl
```

**Comment by killmasta93** [comment]
Hi @rauldpm I was testing and it worked also but not sure if @jesse-zhangh has had this issue is that after doing that it does now show any events on the wazuh dashboard?

Thank you

**Comment by rauldpm** [comment]
Hi @killmasta93

What version/tag of Wazuh are you deploying with Docker? Is it a multi node deployment or is it a single node? The answers given above are intended for a single node environment.

It would be necessary to know if you have carried out all the steps indicated above (both for the admin user and for other users) or to which specific user you have changed the password.

As a note, as of v4.3.7 this procedure does not need to be done, but if the version is v4.3.6 included or earlier and the deployment you are doing has already been lifted, it is necessary to change the password in the `/etc/filebeat/filebeat.yml` file in the manager container:

- docker exec -it single-node_wazuh.manager_1 sed -i "s/SecretPassword/your_admin_password/g" /etc/filebeat/filebeat.yml
- docker exec -it single-node_wazuh.manager_1 service filebeat restart

This last command will restart the `wazuh-manager` service too, If this was the problem, you should be able to see alerts in the WUI again.

Regards, Raúl.

**Comment by killmasta93** [comment]
Hi @rauldpm thank you so much for the reply it seems that i had to edit the filebeat.yml with that did the trick thank you so much

**Comment by rauldpm** [comment]
Hello @jesse-zhangh and @killmasta93, I proceed to close the issue due to inactivity, do not hesitate to reopen it if necessary.

Regards, Raúl.

**Comment by Trufax** [comment]
i have a question, i see the following users as well in the internal_users.yml:

kibanaro
logstash
readall
snapshotrestore

How is the process for changing them as well ? Or are they even required or can i delete them entirely. 

Thanks for the help!

**Comment by killmasta93** [comment]
hI @rauldpm quick question im doing the same steps as above for multi node but when i try to change the password on the wazuh indexer part i get this error 

```
Security Admin v7
Will connect to localhost:9300
ERR: Seems there is no OpenSearch running on localhost:9300 - Will exit
```
![image](https://user-images.githubusercontent.com/13953629/201818013-b6bb1ff0-cdbd-4a24-9f31-51219c95738a.png)

**Comment by geez0r** [comment]
Yepp, I ran into this too; 
This is such a fundamental thing (especially when the UI has this option), this should be implemented or at least the workaround highlighted in the documentation.

**Comment by killmasta93** [comment]
i  solved with this command hope this helps
`
bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -f /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml -nhnv -cacert  $CACERT -cert $CERT -key $KEY -p 9300 -icl -h ip_of_indexer in which you are executing`

**Comment by shamash87** [comment]
Ok. thx, it works :D

**Comment by arosario513** [comment]
I'm having the same issue in where the API doesn't run after changing the password

**Comment by mattish91** [comment]
> * le-node/confg/wazuh-indexer/internal-users.yml

crap xD

Just followed this and now my container is broken

Docker starts up fine no errors there BUT when visiting my wazuh dashboard im getting this:
`{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred."}`

**Comment by KuasarCloud** [comment]
Hi Wazuh Team,

When I run on my 4.5.0 

`bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -f /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml -nhnv -cacert  $CACERT -cert $CERT -key $KEY -p 9300 -icl -h ip_of_indexer`

I'm getting this error, not an http protocol

```
Trace:
java.lang.RuntimeException: error while performing request
	at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:963)
	at org.opensearch.client.RestClient.performRequest(RestClient.java:332)
	at org.opensearch.client.RestClient.performRequest(RestClient.java:320)
	at org.opensearch.security.tools.SecurityAdmin.execute(SecurityAdmin.java:462)
	at org.opensearch.security.tools.SecurityAdmin.main(SecurityAdmin.java:159)
Caused by: org.apache.http.ProtocolException: Not a valid protocol version: This is not an HTTP port
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:209)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:245)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.http.ParseException: Not a valid protocol version: This is not an HTTP port
	at org.apache.http.message.BasicLineParser.parseProtocolVersion(BasicLineParser.java:148)
	at org.apache.http.message.BasicLineParser.parseStatusLine(BasicLineParser.java:366)
	at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:112)
	at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:50)
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:207)
	... 11 more
```
