### ISSUE TITLE
Wazuh dashboard server is not ready yet #4.5.2 #Docker

### ISSUE THREAD

**Issue by SylvainDx** [wazuh/wazuh-docker#999]
Hello
I'm trying to deploy Wazuh on Docker with single-node configuration.
I followed step by step instruction but end up with a DashBoard not ready...

I deleted every thing and start over without any change on the docker compose files withou any more succes.

I've got this on Manager : 
023-09-17T16:19:03.383Z	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(elasticsearch(https://wazuh.indexer:9200)): Get "https://wazuh.indexer:9200": dial tcp 172.25.0.3:9200: connect: connection refused

on Dashoboard
[ConnectionError]: connect ECONNREFUSED 172.25.0.3:9200 | type=log @timestamp=2023-09-17T16:20:03Z tags=["error","opensearch","data"] pid=39

On Indexer in the /var/log/wazuh-indexer/opensearch.log
[2023-09-16T18:01:18,754][ERROR][o.o.b.Bootstrap          ] [wazuh.indexer] Exception
org.opensearch.OpenSearchException: failed to bind service
        at org.opensearch.node.Node.<init>(Node.java:1124) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.node.Node.<init>(Node.java:361) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) [opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) [opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) [opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) [opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) [opensearch-cli-2.6.0.jar:2.6.0]
        at org.opensearch.cli.Command.main(Command.java:101) [opensearch-cli-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) [opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) [opensearch-2.6.0.jar:2.6.0]
Caused by: java.nio.file.AccessDeniedException: /var/lib/wazuh-indexer/nodes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:700) ~[?:?]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?]
        at java.nio.file.Files.createDirectories(Files.java:793) ~[?:?]
        at org.opensearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:313) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:251) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:311) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.node.Node.<init>(Node.java:464) ~[opensearch-2.6.0.jar:2.6.0]
        ... 11 more
[2023-09-16T18:01:18,759][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [wazuh.indexer] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: OpenSearchException[failed to bind service]; nested: AccessDeniedException[/var/lib/wazuh-indexer/nodes];
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-2.6.0.jar:2.6.0]
        at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-2.6.0.jar:2.6.0]
Caused by: org.opensearch.OpenSearchException: failed to bind service
        at org.opensearch.node.Node.<init>(Node.java:1124) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.node.Node.<init>(Node.java:361) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.6.0.jar:2.6.0]
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /var/lib/wazuh-indexer/nodes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:700) ~[?:?]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?]
        at java.nio.file.Files.createDirectories(Files.java:793) ~[?:?]
        at org.opensearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:313) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:251) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:311) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.node.Node.<init>(Node.java:464) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.node.Node.<init>(Node.java:361) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.6.0.jar:2.6.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.6.0.jar:2.6.0]
        ... 6 more

thanks for your assistance !

**Comment by SylvainDx** [comment]
according to #771

docker ps |grep wazuh
178f8519695e   wazuh/wazuh-dashboard:4.5.2                    "/entrypoint.sh"         24 hours ago   Up 22 hours   443/tcp, 0.0.0.0:8443->5601/tcp, :::8443->5601/tcp    wazuh-wazuh.dashboard-10

a1e6b4203395   wazuh/wazuh-manager:4.5.2                      "/init"                  24 hours ago   Up 22 hours   0.0.0.0:1514-1515->1514-1515/tcp, :::1514-1515->1514-1515/tcp, 0.0.0.0:514->514/udp, :::514->514/udp, 0.0.0.0:55000->55000/tcp, :::55000->55000/tcp, 1516/tcp   wazuh-wazuh.manager-10

8599e3d36c50   wazuh/wazuh-indexer:4.5.2                      "/entrypoint.sh open…"   24 hours ago   Up 22 hours   0.0.0.0:9200->9200/tcp, :::9200->9200/tcp                                                                                                                       wazuh-wazuh.indexer-10

but the curl return an error : 
curl  https://localhost:9200/_cluster/health?pretty -k -u admin:SecretPassword
curl: (35) error:0A000126:SSL routines::unexpected eof while reading

**Comment by alphaDev23** [comment]
Why is this issue still open after almost a year.  There are multiple issues on the same.  The single-node docker deployment does not work, there are numerous permission errors in the log files, and the indexer fails to properly come up.  Has anyone tested this because it also doesn't work in 4.7.

**Comment by mqu** [comment]
same error here : #1699 ; seems to work with 4.10.1 ; I am trying with latest stable (4.11.2) having same troubles.

**Comment by coderMohammed1** [comment]
I think that we can not edit the password LOL
